name: Create Escrow

on:
  workflow_call:
    inputs:
      CHAIN_ID: { type: number, required: true }
      DAILY_VOLUME_TARGET: { type: number, required: true }
      DURATION: { type: number, required: true }
      EXCHANGE_NAME: { type: string, required: true }
      EXCHANGE_ORACLE_ADDRESS: { type: string, required: true }
      EXCHANGE_ORACLE_FEE: { type: number, required: true }
      GAS_WARN_THRESHOLD: { type: number, required: true }
      RECORDING_ORACLE_ADDRESS: { type: string, required: true }
      RECORDING_ORACLE_FEE: { type: number, required: true }
      REPUTATION_ORACLE_ADDRESS: { type: string, required: true }
      REPUTATION_ORACLE_FEE: { type: number, required: true }
      REWARD_AMOUNT: { type: number, required: true }
      REWARD_TOKEN: { type: string, required: true }
      START_DELAY: { type: number, required: true }
      SYMBOL: { type: string, required: true }
    secrets:
      WEB3_RPC_URL: { required: true }
      WEB3_PRIVATE_KEY: { required: true }
      SLACK_WEBHOOK_URL: { required: true }

jobs:
  create-escrow:
    runs-on: ubuntu-latest
    concurrency:
      group: create-escrow-${{ inputs.SYMBOL }}-${{ inputs.EXCHANGE_NAME }}
      cancel-in-progress: false
    env:
      CHAIN_ID: ${{ inputs.CHAIN_ID }}
      DAILY_VOLUME_TARGET: ${{ inputs.DAILY_VOLUME_TARGET }}
      DURATION: ${{ inputs.DURATION }}
      EXCHANGE_NAME: ${{ inputs.EXCHANGE_NAME }}
      EXCHANGE_ORACLE_ADDRESS: ${{ inputs.EXCHANGE_ORACLE_ADDRESS }}
      EXCHANGE_ORACLE_FEE: ${{ inputs.EXCHANGE_ORACLE_FEE }}
      GAS_WARN_THRESHOLD: ${{ inputs.GAS_WARN_THRESHOLD }}
      RECORDING_ORACLE_ADDRESS: ${{ inputs.RECORDING_ORACLE_ADDRESS }}
      RECORDING_ORACLE_FEE: ${{ inputs.RECORDING_ORACLE_FEE }}
      REPUTATION_ORACLE_ADDRESS: ${{ inputs.REPUTATION_ORACLE_ADDRESS }}
      REPUTATION_ORACLE_FEE: ${{ inputs.REPUTATION_ORACLE_FEE }}
      REWARD_AMOUNT: ${{ inputs.REWARD_AMOUNT }}
      REWARD_TOKEN: ${{ inputs.REWARD_TOKEN }}
      START_DELAY: ${{ inputs.START_DELAY }}
      SYMBOL: ${{ inputs.SYMBOL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install Corepack
        run: npm install -g corepack
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run launch-campaign script
        run: node launch-campaign.js
        env:
          WEB3_RPC_URL: ${{ secrets.WEB3_RPC_URL }}
          WEB3_PRIVATE_KEY: ${{ secrets.WEB3_PRIVATE_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}